name: BackVault
version: 1.0
main: org.sunpowder.backvault.backvault
api-version: 1.19
authors: [Sunpowder]
commands:
  backvault:
    description: Reload plugin configuration
    permission: backvault.reload
    usage: /backvault reload

permissions:
  backvault.reload:
    description: Allows reloading of BackVault configuration
    default: op
